// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Shape = {
  id: number,
  type: string | undefined,
  x: number,
  y: number,
  width: number,
  height: number,
  color: string | undefined,
  rotation: number,
  createdBy: __Identity,
  createdAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const Shape = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U32},
        { name: "type", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "x", algebraicType: __AlgebraicTypeValue.F32},
        { name: "y", algebraicType: __AlgebraicTypeValue.F32},
        { name: "width", algebraicType: __AlgebraicTypeValue.F32},
        { name: "height", algebraicType: __AlgebraicTypeValue.F32},
        { name: "color", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "rotation", algebraicType: __AlgebraicTypeValue.F32},
        { name: "createdBy", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Shape): void {
    __AlgebraicTypeValue.serializeValue(writer, Shape.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Shape {
    return __AlgebraicTypeValue.deserializeValue(reader, Shape.getTypeScriptAlgebraicType());
  },

}

export default Shape;


